<?php

$titulo = array('Panamá', 'Un lugar privilegiado.','PANAMÁ: MUCHO MÁS QUE EL CANAL','CULTURA','MONEDA','VESTIMENTA');

$menu = array('Información', 'Destinos', 'Eventos','Contactenos','Idioma','Español','Inglés');

$contenido = array('Hace tres millones de años, el istmo de Panamá emergió del mar y cambió el mundo para siempre. Dividió un océano y unió dos continentes, lo que provocó uno de los eventos de evolución natural más importantes de la historia del mundo. Hoy en día, este estrecho puente de tierra en Centroamérica es el hogar de más especies de aves y árboles que en todo Norteamérica. Te invitamos a descubrir la belleza de sus paisajes, su rica cultura y un sinfín de actividades turísticas que están a tu alcance.','Panamá es mundialmente reconocido por sus 48 millas de canal que unen el océano Pacífico con el océano Atlántico. Cada año más de un millón de personas visitan el Canal de Panamá y presencian esta maravilla de la ingeniería. En la ciudad de Panamá podrás disfrutar de restaurantes de calidad, excitante vida nocturna y casinos. Panamá ha atraído a algunas de las marcas más famosas del mundo para abrir sus tiendas en estas tierras. Turistas de todo el mundo visitan nuestro país y descubren una hermosa ciudad cosmopolita, con todas las comodidades que se esperan de un centro de negocios y turismo.','Panamá posee una multiplicidad cultural que lo hace único en la región, a lo que contribuye además la constante presencia de visitantes de todas partes del mundo. El origen de esta singular mezcla cultural es sin duda la característica de encrucijada que siempre ha tenido el país, pero también lo es la conexión intensa de Panamá con el mar que la hace muy parecida a una isla del Caribe. Es particularmente rica, pues aunque proviene de orígenes culturales y tradiciones muy diversas, ha sido estimulada por el ambiente de tolerancia y armonía que siempre ha imperado en el territorio.','EL US Dólar circula libremente. La moneda panameña, el Balboa, tiene paridad con la de Estados Unidos.','Se recomienda traer ropa liviana, telas delgadas y frescas. Si vistas las tierras alta, conviene llevar prendas que abriguen.');

$footer = array('Tu Sitio 2018','Declaración de Privacidad');
?>