<?php
$titulo = array('Panama', 'Panama a privileged place.','PANAMA: MUCH MORE THAN THE CANAL','CULTURE','CURRENCY','CLOTHING');

$menu = array('Information', 'Destiny', 'Events','Contact','Language','Spanish','Enlgish');


$contenido = array('Three million years ago, the Isthmus of Panama emerged from the sea and changed the world forever. It divided an ocean and united two continents, which caused one of the most important natural evolution events in the history of the world. Today, this narrow land bridge in Central America is home to more species of birds and trees than in all of North America. We invite you to discover the beauty of its landscapes, its rich culture and endless tourist activities that are within your reach.','Panama is world renowned for its 48 miles of canal that link the Pacific Ocean with the Atlantic Ocean. Every year more than one million people visit the Panama Canal and witness this marvel of engineering. In Panama City you can enjoy quality restaurants, exciting nightlife and casinos. Panama has attracted some of the world\'s most famous brands to open its stores in these lands. Tourists from all over the world visit our country and discover a beautiful cosmopolitan city, with all the comforts expected of a business and tourism center.','Panama has a cultural multiplicity that makes it unique in the region, which also contributes to the constant presence of visitors from all over the world. The origin of this unique cultural mix is undoubtedly the crossroads that the country has always had, but so is Panama\'s intense connection with the sea that makes it very similar to an island in the Caribbean. It is particularly rich, because although it comes from very diverse cultural origins and traditions, it has been stimulated by the atmosphere of tolerance and harmony that has always prevailed in the territory.','THE US Dollar circulates freely. The Panamanian currency, the Balboa, has parity with that of the United States.','It is recommended to bring light clothes, thin and fresh fabrics. If you visit the highlands, it is advisable to wear warm clothes.');

$footer = array('Your Website 2018','Privacy Statement');
?>